spring:
  datasource:
    url: jdbc:postgresql://localhost:32768/el_grande
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: true